---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность указать ФИО, телефон, емейл для оформления заказа
  - Поле ФИО должно быть обязательным.
  - Поле ФИО должно состоять только из букв.
  - Поле ФИО должно содержать от 2-20 символов.
  - Поле телефон должен быть обязательным.
  - Поле телефон должен состоять из цифр и начинаться со знака +.
  - Поле телефон должно содержать до 12 символов.
  - Поле емейл должно быть обязательным.
  - Поле емейл должно проверяться на корректность.
  - Уведомления об ошбках при заполенении данных должны быть информативными и указывать на конкретную ошибку в каждом поле.
  - Поля ввода данных должны содержать плейсхолдеры и подсказки формата данных.
  - Пользователь должен иметь возможность после оформления заказа переходить на страницу оплаты
  - Пользователь должен иметь возможность ознакомится с документом об обработке персональных данных согласно 152-ФЗ
  - Пользователь должен иметь возможность ознакомится с данными об условиях доставки, возврата, способы оплаты заказа
  - Пользователь должен иметь возможность видеть результат действий на сайте в виде уведомлений при добавлении в корзину
  - Пользователь должен иметь возможность видеть языковую версию, в которой сейчас находится
  - Меню яызковой версии не должно быть открыто по умолчанию
  - Пользователь должен иметь возможность сбрасывать фильтр категорий
  - Пользователь должен иметь возможность видеть список категорий без дополнительных действий
  - Пользователь должен иметь возможность перейти на гавную страницу магазина через клик по названию или логотипу в шапке
  - Пагинация в каталоге должна быть реализована через номера страниц, чтобы пользователь мог быстрее переходить между страницами
  - Меню в мобильной вверсии должно быть компактным и вемещаться в одну строку. Для экономии пространства можно исползовать иконки корзины вместо слова.
  - Фильтры в мобильной вверсии должны быть компактными. По умолчанию должны быть скрыты и раскрываться при клике на иконку бургера.
